version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: UTC
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: scope
    rebase-strategy: auto
    reviewers: []
    allow:
      - dependency-type: "all"
    groups:
      eslint:
        patterns:
          - "eslint"
          - "@eslint/*"
          - "eslint-*"
          - "@stylistic/*"
      markdown:
        patterns:
          - "markdownlint*"
      mqtt:
        patterns:
          - "mqtt"
      chartjs:
        patterns:
          - "chart.js"
